services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine3.17
    volumes:
      - my_db:$PGDATA
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

volumes:
  my_db:
